### ISSUE TITLE
MySQL 5.6 with built-in memcache supported?

### ISSUE THREAD

**Issue by rh0dium** [django-pylibmc/django-pylibmc#27]
Hey there,

I'm pulling my hair out trying to get this to talk to the MySQL 5.6 new built-in memcache server.  I'm curious if you have been able to do this or not.  Apparently it's memcache compliant but I can't figure out how to get it functioning.  I can do the queries at a telnet session and verify that yes they show up but I can't get this working with django in any way shape or form.

I pinging you to see if you or anyone you know has successfully gotten django to use this combination or am I stomping into new territory?

References:
- http://dev.mysql.com/doc/refman/5.6/en/innodb-memcached-setup.html
- http://chipersoft.com/p/MySQL-via-Memcache/ (Great setup and install)

Thanks so much!!

**Comment by jwhitlock** [comment]
@rh0dium - I hope you are OK after banging your head for 7 months now.  I don't know of anyone using MySQL's built-in memcache server - you could be one of the first.  Unless it how [memcachier](https://www.memcachier.com) secretly works.  It's really easy to setup a memcached server, so most people go that route.

Some things that may help:

[libmemcached](http://libmemcached.org/libMemcached.html) includes [memcapable](http://libmemcached.org/Memcapable.html), a program for verifying a memcached-compliant interface. It's very possible that the MySQL folks use it to verify they comply to the protocols.  You can use it to confirm you have MySQL 5.6 correctly setup.  When testing against memcached, I get a failure on the `ascii verbosity` test (Errno: 60 Operation timed out), but the other tests pass.  This may have interesting results beyond the telnet test.

Django requires configuration to configure the cache, as well as adding code to use the cache where you want it.  It's non-trivial - [read the docs](https://docs.djangoproject.com/en/1.8/topics/cache/).

I'm closing this because it is pretty out-of-scope for this project.  It's worth a good blog post if you can make it work.  If you can't, you'll get a larger audience to help at [ServerFault](http://serverfault.com)
