### ISSUE TITLE
This project needs a maintainer.

### ISSUE THREAD

**Issue by jbalogh** [django-pylibmc/django-pylibmc#31]
### OSS project looking for a good home

I haven't worked in the Django world for a few years so I don't have any motivation to maintain this project. Most of the maintenance involves keeping up with the release cycle for Django.

**Comment by jwhitlock** [comment]
I can help.

**Comment by jbalogh** [comment]
Thank you John! :trophy:

**Comment by ghinch** [comment]
Great news, thanks for stepping up @jwhitlock!

**Comment by jwhitlock** [comment]
My plan is to release 0.6.0 in a few days, with:

* Support for Django 1.4 through 1.7, plus the 1.8 release candidate
* Support for Python 2.6, 2.7, 3.3, 3.4 (requiring pylibmc 1.4.1)
* Add some auto-QA, such as pep8 testing
* Match `timeout=0` behavior to Django's default timeout

Any others that should make the 0.6.0 cut?

@jbalogh - can you add my pipy username (`John.Whitlock`) to the owner or maintainers list?

**Comment by jbalogh** [comment]
> @jbalogh - can you add my pipy username (John.Whitlock) to the owner or maintainers list?

:+1:

**Comment by jwhitlock** [comment]
[v0.6.0 released](https://pypi.python.org/pypi/django-pylibmc/0.6.0).  It includes:

- Support for Django 1.4 through 1.8 (released yesterday),
- Support for Python 2.6, 2.7, 3.3, 3.4
- Requires pylibmc 1.4.1
- Omitting the timeout gets the default timeout in Django 1.6 and higher (rather than "never expire")

There's more I wanted to add, but that feels like a good first maintenance release.
