### ISSUE TITLE
0.6.1 Release?

### ISSUE THREAD

**Issue by jarcoal** [django-pylibmc/django-pylibmc#33]
Can we get a new release that includes https://github.com/django-pylibmc/django-pylibmc/commit/151ecbeade7e05aef5cac257eaa650b833fff314 ?

**Comment by osantana** [comment]
:+1: for a new release that include  #32 :)

**Comment by m1schka** [comment]
what's the status on this? I would love to use this with Django 1.9

**Comment by bforchhammer** [comment]
Yes please, Django 1.9 is not usable for us without this change. :)

**Comment by orokusaki** [comment]
+1

@jwhitlock do you know who the django-pylibmc organization is run by? it has no public members. Should somebody else take over this? There hasn't been a single commit or release since April of this year, yet this is the only reasonable library for using Django with memcached over the weir (e.g., Heroku + Memcachier).

Note: I've been using django-pylibmc.git@151ecbeade7e05aef5cac257eaa650b833fff314 - it works fine.

**Comment by jwhitlock** [comment]
Yeah, who runs this org? *checks github, PyPi* Oh, It's me. And @jbalogh, but he added me because he's not working with Python / Django on a daily basis, as he said in #31.

I'll cut a new 0.6.1 release, which I meant to do before 1.9 was released.  However, if you don't need the features of django-pylibmc, you should consider using Django's [built-in support for memcache](https://docs.djangoproject.com/en/1.9/topics/cache/#memcached)

**Comment by jwhitlock** [comment]
django-pylibmc 0.6.1 released: https://pypi.python.org/pypi/django-pylibmc/0.6.1

**Comment by orokusaki** [comment]
@jwhitlock thanks for the release!
