### ISSUE TITLE
Add edmorley to repo owners / package maintainers

### ISSUE THREAD

**Issue by jwhitlock** [django-pylibmc/django-pylibmc#55]
@edmorley is doing good work getting this project in sync with Django upstream. I think it makes sense to add him to the maintainers list so he can merge his own changes and make new releases.

@edmorley is that something you want to be responsible for?

**Comment by edmorley** [comment]
Hi @jwhitlock, sorry for not replying sooner. In Feb this year we migrated from memcached to Redis (and to be honest haven't looked back), and so are now using [django-redis](https://github.com/niwinz/django-redis) rather than django-pylibmc. I've also picked up maintenance of several other open source projects, so would struggle to find the time to work any more on django-pylibmc. Thank you for the very kind offer though! :-)

**Comment by jwhitlock** [comment]
@edmorley no problem, we moved to redis with django-redis for my projects too 😬. Good job picking up more maintenance!
